### ISSUE TITLE
Dbt deps issue

### ISSUE THREAD

**Issue by dmasip-rxd** [calogica/dbt-expectations#13]
Running `dbt deps` with the following `packages.yml`

```yml
packages:

  - git: "https://github.com/calogica/dbt-expectations.git"
    revision: 0.2.0

  - package: fishtown-analytics/dbt_utils
    version: 0.5.1
```

I get:

```
Running with dbt=0.17.0
Encountered an error:
Version error for package fishtown-analytics/dbt_utils: Could not find a satisfactory version from options: ['=0.5.1', '>=0.6.0', '<0.7.0']

```

It's confusing since I'm actually running with dbt_utils version `0.5.1`. Is this expected?
