### ISSUE TITLE
Table level expectations erroring out with Python code message

### ISSUE THREAD

**Issue by vieiraAlexandre** [calogica/dbt-expectations#144]
Hi, 

The following DBT expectations for table level data checks seemed to have stopped working without a clear cause yet:
- expect_table_columns_to_match_ordered_list
- expect_table_column_count_to_be_between
- expect_table_columns_to_contain_set
- expect_table_column_count_to_equal
- expect_table_columns_to_match_set

When running the dbt test command it outputs a message seemingly from a Python context:
`'str' object has no attribute 'database'`

Could it be related to the way the macro reads the information received from Google BigQuery API? They did work until a certain point in time last week. On the other hand, the expectations for columns seem to keep working just fine.

Currently got these versions for dbt_expectations, dbt-bigquery and dbt. Would there be any (new) dependency clash?
**packages.yml**
```
packages:
  - package: calogica/dbt_expectations
    version: 0.5.1
  - package: dbt-labs/dbt_utils
    version: 0.8.0
```

**Pipfile**
```
[packages]
dbt-bigquery = "==1.0.0"
```

**DBT version**
```installed version: 1.0.1```
