### ISSUE TITLE
filter_by needed for all methods

### ISSUE THREAD

**Issue by eric3kim** [calogica/dbt-expectations#15]
It will be great if we can limit the data set. Some tables could be huge and it just takes too long to complete within CI pipeline.

**Comment by clausherther** [comment]
Hi @eric3kim, all tests, where applicable have a `row_condition` parameter that should work for this purpose, although I need to do a better job documenting this. Could you let me know which ones you're seeing that don't have this?

**Comment by eric3kim** [comment]
thanks! good to know.  I figured. so row_condition = <where clause>? I have not tried this so I will with the ones that I need. Thanks!

**Comment by clausherther** [comment]
Yes, you'd just add something like 
```
  - name: my_table
    tests:
        - dbt_expectations.expect_column_pair_values_to_be_equal:
            column_A: col_numeric_a
            column_B: col_numeric_a
            row_condition: col_c = 'some_value'
```
I'm going to close this issue. Feel free to reopen if this isn't working for you.
