### ISSUE TITLE
Syntax error with take_diff=False in expect_column_values_to_be_within_n_moving_stdevs test 

### ISSUE THREAD

**Issue by karanhegde** [calogica/dbt-expectations#177]
Hi, when the `expect_column_values_to_be_within_n_moving_stdevs` test is used with the parameter `take_diff=False`, it errors out with a couple of SQL syntax issues, [a trailing comma](https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql#L69) (_atleast with BigQuery_) and a [missing alias](https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql#L93). 

Sample config:
```
- dbt_expectations.expect_column_values_to_be_within_n_moving_stdevs:
    sigma_threshold: 2
    date_column_name: "day"
    take_diffs: False
    trend_periods: 365
```

The fix is straightforward, happy to submit a PR for this if that works!
