### ISSUE TITLE
expect_select_column_values_to_be_unique_within_record not consistent with dbt built-in test unique

### ISSUE THREAD

**Issue by greghor** [calogica/dbt-expectations#183]
hi, 

I noticed that the dbt-expectations test `expect_select_column_values_to_be_unique_within_record` passes on some of my table while the built-in dbt test `unique` fails. 

![image](https://user-images.githubusercontent.com/16280126/183875951-e8282be3-fbec-40ee-8de1-c5c0a2246d3b.png)

After checking the value, the column id_version does have duplicates, which makes me think that `expect_select_column_values_to_be_unique_within_record` doesn't behave properly. 

Here is how I use the dbt-expectations test

```
models:
  - name: my_table
    tests:
      - dbt_expectations.expect_select_column_values_to_be_unique_within_record:
          column_list: [id_version]
```

Versions:
```
dbt-expectations: 0.5.8
dbt-core: 1.2.1
dbt-bigquery: 1.2.0 
```
