### ISSUE TITLE
--store-failures with query context

### ISSUE THREAD

**Issue by artemboiko1** [calogica/dbt-expectations#185]
Hi!

I have question / suggestion regarding behaviour of `--store-failures` when used together with [dbt-expectations](https://github.com/calogica/dbt-expectations).

We are looking to use [dbt-expectations](https://github.com/calogica/dbt-expectations), but we are lacking some traceability features. 

Let's look at this meaningless column level assertion / test (from https://github.com/dbt-labs/jaffle_shop):
```
  - name: orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
                min_value: 10
                max_value: 40
```

When  dbt is run with `--store-failures`, single boolean column will be created in the persistent storage. To make this data source of truth and actionable, we want to add context or details to the results of the query. For example:

```
  - name: orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
                query_context: 'order_id, status'
                min_value: 10
                max_value: 40
```

This can be archived with simple changes to the macros. You can see example here:

https://github.com/calogica/dbt-expectations/compare/main...badal-io:dbt-expectations:add_failure_context

This way, result table can have more context and details (row-level, in some cases), which might be useful not just for us.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/108079274/183932789-1ed1f6ac-56a7-4500-9e97-ee25fcede2c7.png">

Would love to get some feedback feasibility of this. We are happy to create PR from our side.
