### ISSUE TITLE
Tests that expect regex patterns are painful to use in BigQuery

### ISSUE THREAD

**Issue by adamcunnington-mlg** [calogica/dbt-expectations#190]
Functions such as [expect_column_values_to_match_regex](https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/string_matching/expect_column_values_to_match_regex.sql) are painful to use in BigQuery because of the intersection of YAML escape sequences, BigQuery escape sequences and implementation of the tests, by dbt-expectations (I'm not sure actually if dbt-core has some responsibility here to fix this so do say if the fix doesn't belong here).

Given some trivial regex expression, `"\d{4}"`, in BigQuery, I would make use of raw strings to avoid illegal escape sequences, e.g. `r"\d{4}"` but dbt-expectations/dbt expects my yaml to be a string and so I can't use `r` otherwise it'll be interpreted as `'r"\d{4}"'`.

Probably dbt-expectations should be smart enough to insert r in front of the string if the adapter supports it (such as BigQuery).

In the meantime, I probably have to double escape the `\`. Once to satisfy YAML escaping and twice to satisfy BigQuery escaping when a raw string is not used.

E.g. I probably need to do:
```yaml
    regex: "\\\d{4}" # note that the encasing "" are irrelevant here.
```

**Comment by clausherther** [comment]
Thanks @adamcunnington-mlg for raising this issue! I don't have a ton experience using regex on BigQuery, but this is good to know. One thing to always keep in mind is that all we're doing in dbt is generate SQL strings, which sometimes results in these weird quoting and escape scenarios.
In your example, what should the fully rendered SQL look like? 
Re: your suggestion, happy to make/merge changes to the BigQuery (and other) implementations if that eases the pain.
Would you be interested in doing a PR for this?

**Comment by adamcunnington-mlg** [comment]
Thanks @clausherther.

Here is what I expected:

my dbt YAML
```yaml
columns:
- name: time
   tests:
   - dbt_expectations.expect_column_values_to_match_regex:
       regex: "^\\d{4}-\\d{2}$"  # unfortunately, I'm not sure the double \ could be avoided here because we have to satisfy YAML escaping regardless
```

compiled SQL
```sql
...
regexp_instr(title, r'^\w{3}-\d{2}$', 1, 1)
...
```

Instead, the `r` is not present in final SQL and so I had to use this horrible escape sequence:
YAML:
```
columns:
- name: time
   tests:
   - dbt_expectations.expect_column_values_to_match_regex:
       regex: "^\\\\d{4}-\\\\d{2}$"
```

which leads to compiled SQL:
```sql
...
regexp_instr(title, '^\\w{3}-\\d{2}$', 1, 1)
...
```
