### ISSUE TITLE
Q: Possible to used "+" syntax to apply tests to whole directories in dbt_project.yml? 

### ISSUE THREAD

**Issue by samLozier** [calogica/dbt-expectations#209]
I've been really liking this package, with the possible issue that I'm finding it a little tedious to repeat tests over and over again for each model in a project. 

So far I haven't been able to figure out if it's possible to apply a test whole directory in a given project. For example, this would be a project-level sanity check test (currently not working): 

```
#dbt_project.yml

models:
  +tests:
    - dbt_expectations.expect_table_row_count_to_be_between:
        min_value: 1 
```

Is there a slick way to do something like this, or will I need to write some kind of script to parse/edit yml files in bulk?
