### ISSUE TITLE
expect_column_distinct_count_to_equal fails if there is no data!

### ISSUE THREAD

**Issue by adamcunnington-mlg** [calogica/dbt-expectations#214]
We use expect_column_distinct_count_to_equal to assert there are x distinct values.

If there are no rows, there are 0 distinct values - but clearly this shouldn't fail when there are no rows.

Is it right for the test to be tweaked so this doesn't fail - or do you think I should include some where condition? What would my where condition be to say "where there are rows"? Maybe it's a test-specific arg that you should support which acts as a flag for the behaviour?

Keen for thoughts, thanks.

**Comment by clausherther** [comment]
Hi @adamcunnington-mlg, which DW platform are you using? On my Postgres, BigQuery and Snowflakes instances, this passes:
```yaml
          - dbt_expectations.expect_column_distinct_count_to_equal:
              row_condition: 1=2 # to simulate an empty table
              value: 0
```
