### ISSUE TITLE
You have 3 'p's in upper in the documentation, meaning the samples error when used

### ISSUE THREAD

**Issue by Mark-Robinson** [calogica/dbt-expectations#218]
For example, you have:

```
models: # or seeds:
  - name: my_model
    tests:
    - dbt_expectations.expect_table_columns_to_not_contain_set:
        column_list: ["col_a", "col_b"]
        transform: uppper # (Optional)
```

when really it should be:

```
models: # or seeds:
  - name: my_model
    tests:
    - dbt_expectations.expect_table_columns_to_not_contain_set:
        column_list: ["col_a", "col_b"]
        transform: upper # (Optional)
```

(Notice u**ppp**er vs u**pp**er)
