### ISSUE TITLE
Update calogica/dbt_date version.

### ISSUE THREAD

**Issue by eivl** [calogica/dbt-expectations#277]
During maintenance update to dbt-expectations version 0.9.0 I get an message about dbt_date having an update available. 

![image](https://github.com/calogica/dbt-expectations/assets/132364/9f86f596-5b67-4714-ba63-e8efebc22c82)

I think it does not update itself due to this:

```YML
packages:
  - package: calogica/dbt_date
    version: [">=0.8.0", "<0.9.0"]
```

Now in my mind, updating the underlying package would work. However #271 did an update a few weeks ago and I'm not sure its safe to just update the dbt_date package. I have tested this myself without finding any issues during install. 

My suggestion is to just do it like so:

```YML
packages:
  - package: calogica/dbt_date
    version: [">=0.9.0", "<0.10.0"]
```

I made an PR #278 with this change, would love some feedback if this is correct or not.
