### ISSUE TITLE
Integration test fails depending of the time of the day

### ISSUE THREAD

**Issue by b-per** [calogica/dbt-expectations#30]
Hi! 

 I have been running the integration tests and the following test fails depending on the time of the day (before or after midday)

```
  - name: timeseries_hourly_data_extended
    columns:
      - name: date_hour
        tests:
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: hour
              interval: 12
```

`timeseries_hourly_data_extended` uses `date_spine` up to to today, while excluding it (as described in dbt-utils: "_This macro returns the sql required to build a date spine. The spine will include the start_date (if it is aligned to the datepart), but it will not include the end_date"_)

When running the test at 2 pm, going back 12 hours makes it 2 am, which is still after the last record, knowing that date_spine excludes the `end_date`, so the test fails.

Would it make sense to change this to 24?
https://github.com/calogica/dbt-expectations/blob/0a64e5e46086d666b78a7d427d122719898b14ff/integration_tests/models/schema_tests/schema.yml#L90

Cheers,
