### ISSUE TITLE
expect_column_values_to_be_decreasing doesn't uses wrong order when sorting

### ISSUE THREAD

**Issue by maxmarcon** [calogica/dbt-expectations#317]
### Is this a new bug in dbt-expectations?

- [X] I believe this is a new bug in dbt-expectations
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`expect_column_values_to_be_decreasing` sort values in the wrong order. [Here](https://github.com/calogica/dbt-expectations/blob/0.10.3/macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql#L30) it should be: ```order by sort_column desc```

### Expected Behavior

With the following view generated with an order by clause (see below):

```
|period_start|
+------------+
|  2024-07-01|
|  2024-07-01|
|  2024-07-01|
|  2024-07-01|
|  2024-07-01|
|  2024-06-01|
|  2024-06-01|
|  2024-06-01|
|  2024-06-01|
|  2024-06-01|
```

This test should pass:

```yaml
- name: period_start
  data_tests:
   - dbt_expectations.expect_column_values_to_be_decreasing:
         strictly: false
```
Instead, it fails

### Steps To Reproduce

Create a view like the above and run the dbt test

*test.sql:*
```
select *
from
    (
        values
            ('2024-07-01'),
            ('2024-07-01'),
            ('2024-07-01'),
            ('2024-07-01'),
            ('2024-07-01'),
            ('2024-06-01'),
            ('2024-06-01'),
            ('2024-06-01'),
            ('2024-06-01'),
            ('2024-06-01')
    )
    periods(period_start)
    order by period_start desc
```

_schema.yml_:
```
version: 2

models:
  - name: test
    columns:
      - name: period_start
        data_tests:
          - dbt_expectations.expect_column_values_to_be_decreasing:
              strictly: false
```

### Relevant log output

```
07:04:52  Concurrency: 1 threads (target='dev')
07:04:52  
07:04:52  1 of 2 START sql view model dwh.test ........................................... [RUN]
07:04:52  1 of 2 OK created sql view model dwh.test ...................................... [CREATE VIEW in 0.22s]
07:04:52  2 of 2 START test dbt_expectations_expect_column_values_to_be_decreasing_test_period_start__False  [RUN]
07:04:52  2 of 2 FAIL 1 dbt_expectations_expect_column_values_to_be_decreasing_test_period_start__False  [FAIL 1 in 0.17s]
```

### Environment

```markdown
- OS: MacOS
- Python: 3.9.18
- dbt: 1.8.3 (core)
- dbt-expectations: 0.10.3  
```

### Which database adapter are you using with dbt? **Postgres**

Note: dbt-expectations currently does not support database adapters other than the ones listed below.

- Postgres
- Snowflake
- BigQuery
