### ISSUE TITLE
[Feature Request] Allow selecting dbt_expectations tests by tags

### ISSUE THREAD

**Issue by siljamardla** [calogica/dbt-expectations#322]
With dbt column level tests it is possible to tag the test, for example:
```yml
    columns:
      - name: some_column
        data_tests:
          - not_null:
              config:
                tags: some_model_column_tests
```
And then it's possible to make use of those tags in `--select` statements, for example:
```
dbt list --select tag:some_model_column_tests
```
will return 
```
my_dbt_project_name.my_folder.my_model.not_null_my_model_some_column
```

I've tried to add a tag to the configuration of a dbt_expectations test, for example:
```yml
      - dbt_expectations.expect_table_row_count_to_equal:
          value: 0
          group_by: [created_date]
          row_condition: some_column='failed'
          config:
            tag: some_model_tests
            severity: warn
            store_failures: true
```
This does not throw an error when parsing the project. 

However, the tag is not recognised either. When I try to use it in a `--select` statement:
```
dbt list --select tag:some_model_tests
```
I get nothing.
