### ISSUE TITLE
Add test to compare distinct counts between tables

### ISSUE THREAD

**Issue by jeffwhite-indeed** [calogica/dbt-expectations#48]
Can we consider a test that would check that all distinct source records are present on a target table? This could confirm that our warehouse isn't missing any ids. I would imagine it might be similar to the **expect_table_row_count_to_equal_other_table** test, but with a `distinct` allowed?

**Comment by clausherther** [comment]
This could in theory be accomplished today using the base `equal_expression` macro, and we can easily wrap this in a more specific "expectation".

```yaml
  - name: my_model_1
    tests:
        - dbt_expectations.equal_expression:
            expression: count(distinct col1)
            compare_model: ref("my_model_2")
            compare_expression: count(distinct col2)
```
