### ISSUE TITLE
Changes to dispatch in dbt v0.20

### ISSUE THREAD

**Issue by jtcohen6** [calogica/dbt-expectations#78]
Hey Claus! Planning to open this same issue in the `dbt-date` package momentarily :)

### Required code change

We've made a change to `adapter.dispatch`: Instead of passing a `_get_namespaces()` macro to the `packages` arg, you should pass the name of this package (as a string) to the `macro_namespace` arg, which is now the second positional argument.

In practice, this just looks like switching each macro like:
https://github.com/calogica/dbt-expectations/blob/730d195a6e627fd5e2b62d92ba0207ed0da7027d/macros/math/log_natural.sql#L1-L3

To:
```sql
{% macro log_natural(x) -%}
    {{ adapter.dispatch('log_natural', 'dbt_expectations') (x) }}
{% endmacro %}
```

I hope this could be as simple as Find + Replace for `packages=dbt_expectations._get_namespaces()` &rarr; `'dbt_expectations'`.

### For the README

If a user wishes to override/shim this package, instead of defining a var named `dbt_expectations_dispatch_list` (or `dbt_utils_dispatch_list`), they should now define [a config](https://next.docs.getdbt.com/reference/project-configs/dispatch-config) in `dbt_project.yml`, for instance:
```yml
dispatch:
  - macro_namespace: dbt_expectations
    search_order: ['my_project', 'dbt_expectations']  # enable override
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']  # shim for spark
```

### Notes

This change is in dbt v0.19.2 as well. **Both v0.19.2 and v0.20.0 have backwards compatibility for the old syntax**, so there's no huge rush to upgrade. As soon as you do upgrade to the new syntax, you'll need to require `dbt >= 0.19.2` (or just `>=0.20.0`, for simplicity, since you're already making compatibility changes in #69).

See also:
- https://github.com/fishtown-analytics/dbt/issues/3383
- https://next.docs.getdbt.com/reference/dbt-jinja-functions/dispatch
