### ISSUE TITLE
Error after upgrade to 0.3.6

### ISSUE THREAD

**Issue by edbizarro** [calogica/dbt-expectations#89]
With my packages like:

```yaml
packages:
  - package: calogica/dbt_expectations
    version: [">=0.3.0", "<0.4.0"]
  - package: fishtown-analytics/codegen
    version: 0.3.2
  - package: fivetran/fivetran_log
    version: 0.3.1
  - package: fishtown-analytics/audit_helper
    version: 0.3.0
```

I'm getting this error:
```
Running with dbt=0.19.1
Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.
```

But if we pin the version on 0.3.4 everything works fine
