### ISSUE TITLE
Compatibility issue with dbt v0.20.0

### ISSUE THREAD

**Issue by meurant-naude** [calogica/dbt-expectations#94]
Hi there,
I've just upgraded to v0.20.0 to do some evaluation and check for any breaks. I'm getting this error when I run `dbt deps`
```
Running with dbt=0.20.0
Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.
```
This is my package.yml:
```
packages:
- package: dbt-labs/dbt_utils
  version: 0.7.0  
- package: calogica/dbt_expectations
   version: 0.3.7
```
If I remove your package I don't get the error.
```
Running with dbt=0.20.0
Installing dbt-labs/dbt_utils@0.7.0
  Installed from version 0.7.0
```
We use your awesome package extensively. If you could have a look asap, that would be much appreciated.
